# Generated by Django 6.0.1 on 2026-01-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('vajilla', 'Vajilla'), ('sillas', 'Sillas'), ('mesas', 'Mesas'), ('manteles', 'Manteles'), ('cubiertos', 'Cubiertos'), ('cristaleria', 'Cristalería'), ('decoracion', 'Decoración'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Categoría')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por unidad')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['category', 'name'],
            },
        ),
    ]
